#!/usr/bin/env node
// Regenerate references/scripts-catalog.md from script header comments —
// eliminates hand-maintained drift. Convention: first contiguous // block of
// each script is its description; a `Usage:` line adds an examples column.
// Usage: node scripts/generate_scripts_catalog.js [--check]   (--check: exit 1 if stale)
const fs = require('fs'); const path = require('path');
const scriptsDir = path.join(__dirname); const catPath = path.join(__dirname, '..', 'references', 'scripts-catalog.md');
const files = fs.readdirSync(scriptsDir).filter(f => f.endsWith('.js') && !f.startsWith('.')).sort();
const rows = [];
for (const f of files) {
  const src = fs.readFileSync(path.join(scriptsDir, f), 'utf8');
  const m = src.match(/^(?:'use strict';\s*)?(?:\/\/[^\n]*\n)+/);
  let desc = '(no header)';
  if (m) {
    desc = m[0].split('\n').filter(l => l.startsWith('//')).map(l => l.replace(/^\/\/\s?/, '')).join(' ')
      .replace(/Usage:[^\n]*/gi, '').replace(/\s+/g, ' ').trim().slice(0, 160) || '(no header)';
  }
  rows.push({ f, desc });
}
const body = `# Scripts Catalog\n\nAUTO-GENERATED by scripts/generate_scripts_catalog.js — do not edit by hand;\nrun \`node scripts/generate_scripts_catalog.js\` after adding a script.\n\n- total scripts: \`${rows.length}\`\n\n| Script | Description (from header) |\n|---|---|\n` + rows.map(r => `| \`${r.f}\` | ${r.desc.replace(/\|/g, '\\|')} |`).join('\n') + '\n';
if (process.argv.includes('--check')) {
  const cur = fs.readFileSync(catPath, 'utf8');
  if (cur !== body) { console.error('scripts-catalog.md is STALE — regenerate'); process.exit(1); }
  console.log('catalog up to date');
} else { fs.writeFileSync(catPath, body); console.log('catalog regenerated:', rows.length, 'scripts'); }
