#!/usr/bin/env node
// Scaffold a long-running local signing service around an ALREADY-SOLVED
// signer. Turns a one-shot collector into production supply for crawlers:
// POST /sign {input...} -> {token}, GET /health, GET /stats, optional
// keepalive self-check. Zero dependencies (node http + vm).
//
// Usage:
//   node scripts/scaffold_signer_service.js <name> [--port 8787] [--out <dir>]
// Generated layout (mirror of the verbatim harness rules):
//   <dir>/signer.js   — drop your extracted signer verbatim here
//   <dir>/service.js  — the HTTP wrapper (realm setup per recipes)
//   <dir>/TODO.md
//
// The wrapper honors the verified rules: realm-local stubs only (no host
// eval/builtins), real timers with microtask-exception no-ops, a calibration
// hook on boot, and request-scoped fresh clocks.
const fs = require('fs');
const path = require('path');

const args = process.argv.slice(2);
const argOf = (k, d) => { const i = args.indexOf(k); return i >= 0 ? args[i + 1] : d; };
const name = args[0] && !args[0].startsWith('--') ? args[0] : null;
if (!name) { console.error('usage: scaffold_signer_service.js <name> [--port 8787] [--out dir]'); process.exit(2); }
const port = parseInt(argOf('--port', '8787'), 10);
const outDir = path.resolve(argOf('--out', `signer-service-${name}`));

const SERVICE = `#!/usr/bin/env node
// Signing service for ${name} — generated by scaffold_signer_service.js.
// Endpoints:
//   GET  /health          -> {ok, uptimeS, served}
//   GET  /stats           -> {served, errors, lastError, avgMs}
//   POST /sign {input}    -> {token}   (body: JSON with the signer's input fields)
// Rules honored: realm-local stubs only; real timers + microtask no-ops;
// calibration check on boot; fresh clock per request when the signer uses time.
const http = require('http');
const vm = require('vm');
const fs = require('fs');
const path = require('path');

const PORT = parseInt(process.env.PORT || '${port}', 10);
const stats = { served: 0, errors: 0, lastError: null, totalMs: 0, bootedAt: Date.now() };

function nativeFn(n) { const f = { [n]: function () {} }[n]; f.toString = () => \`function \${n}() { [native code] }\`; return f; }
function makeRealm() {
  const sb = {
    console: { log() {}, error() {}, warn() {} },
    setTimeout: (fn, ms) => setTimeout(() => { try { fn(); } catch (e) {} }, ms),
    clearTimeout: t => clearTimeout(t),
    setInterval: (fn, ms) => setInterval(() => { try { fn(); } catch (e) {} }, ms),
    clearInterval: t => clearInterval(t),
    Date, Math, JSON, String, Number, Array, Object,
    Document: nativeFn('Document'), Navigator: nativeFn('Navigator'),
    print: nativeFn('print'),
    // TODO: extend the stub face to exactly what YOUR signer probes
    // (see references/env-rebuild-recipes.md cards 1-7)
  };
  sb.globalThis = sb; sb.window = sb; sb.self = sb;
  vm.createContext(sb);
  return sb;
}

const realm = makeRealm();
vm.runInContext(fs.readFileSync(path.join(__dirname, 'signer.js'), 'utf8'), realm, { filename: 'signer.js' });

// boot calibration: wire whatever in-process oracle your target exposes
// (e.g. a known vector) and crash early instead of serving wrong tokens
// TODO: replace with your calibration, keep the shape:
// const probe = realm.sign('calibration-input');
// if (!probe) { console.error('calibration failed: signer returned empty'); process.exit(1); }

const server = http.createServer((req, res) => {
  const send = (code, obj) => { res.writeHead(code, { 'Content-Type': 'application/json' }); res.end(JSON.stringify(obj)); };
  if (req.method === 'GET' && req.url === '/health') return send(200, { ok: true, uptimeS: Math.round((Date.now() - stats.bootedAt) / 1000), served: stats.served });
  if (req.method === 'GET' && req.url === '/stats') return send(200, stats);
  if (req.method === 'POST' && req.url === '/sign') {
    let body = '';
    req.on('data', c => body += c);
    req.on('end', () => {
      const t0 = Date.now();
      try {
        const input = JSON.parse(body || '{}');
        // TODO: adapt to your signer's actual entry and input shape:
        const token = realm.sign(input.input !== undefined ? input.input : JSON.stringify(input));
        if (!token) throw new Error('signer returned empty (check realm stubs / timers / calibration)');
        stats.served++; stats.totalMs += Date.now() - t0;
        send(200, { token });
      } catch (e) {
        stats.errors++; stats.lastError = e.message;
        send(500, { error: e.message });
      }
    });
    return;
  }
  send(404, { error: 'routes: GET /health, GET /stats, POST /sign' });
});
server.listen(PORT, '127.0.0.1', () => console.error(\`signing service for ${name} on http://127.0.0.1:\${PORT} (signer loaded, realm ready)\`));
`;

fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(path.join(outDir, 'service.js'), SERVICE);
fs.writeFileSync(path.join(outDir, 'signer.js'), '// TODO: paste your EXTRACTED signer verbatim (the whole obfuscated unit,\n// per references/env-rebuild-recipes.md — never a hand-port).\n// Must expose globalThis.sign(input) (or adapt service.js TODO).\n');
fs.writeFileSync(path.join(outDir, 'TODO.md'), `# ${name} signing service TODO\n\n- [ ] paste the verbatim signer into signer.js (exposes globalThis.sign)\n- [ ] extend makeRealm() stubs to the exact probe face (recipes cards 1-7)\n- [ ] wire the boot calibration (known vector; fail fast)\n- [ ] adapt the /sign input mapping in service.js\n- [ ] smoke: curl -X POST localhost:${port}/sign -d '{"input":"test"}'\n- [ ] remember M2 discipline: verify downstream acceptance, not just 200s\n`);
console.log(JSON.stringify({ generated: outDir, files: ['service.js', 'signer.js', 'TODO.md'], port }, null, 1));
